import type { Metadata } from "next";
import { Funnel_Display} from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const funDisplay = Funnel_Display({
    variable: "--font-funnel-display",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <body className={funDisplay.variable}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
